"""A Python module for Qualtrics."""

__author__ = "Sebastian Fest"
__email__ = "sebastian.fest@nhh.no"
__copyright__ = "Copyright (c) 2021 Sebastian Fest"
__license__ = "MIT License"
__version__ = "0.0.1"
__url__ = ""
__download_url__ = ""
__description__ = "A Python module for Qualtrics."
