name: pyqual_testing

on:
  push:
    branches:
      - main

jobs:
  update:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.6
          cache: pip

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Run tests
        run: python -m unittest discover src/tests/


#jobs:
#  run-test:
#    strategy:
#      fail-fast: false
#      matrix:
#        os: [ ubuntu-latest ]
#        python-version: [ "3.11" ]
#
#    name: Test
#    runs-on: ${{ mastrix.os }}

#    steps:
#      -name: Checkout code
#      uses: actions/checkout@v3
#
#      -name: Set up Python
#        uses: actions/csetup-python@v4
#        with:
#          python-version: ${{ python-version }}
#