name: pyqual_testing

on:
  push:
    branches:
      - main

jobs:
  update:
    name: Test
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run tests
        run: python -m unittest discover src/tests/